CREATE TABLE MAGENCY_BILLBOARD (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    TITLE NVARCHAR2(200),
    LOCATION NVARCHAR2(500),
    LAT DOUBLE PRECISION NOT NULL,
    LNG DOUBLE PRECISION NOT NULL,
    WIDTH DOUBLE PRECISION NOT NULL,
    HEIGHT DOUBLE PRECISION NOT NULL,
    IS_LED NUMBER(1) CHECK (IS_LED IN (0,1)) NOT NULL
);

CREATE TABLE MAGENCY_NEWSPAPER (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    TITLE NVARCHAR2(200)
);


CREATE TABLE MAGENCY_SECTION (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    TITLE NVARCHAR2(200),
    NEWSPAPER_ID NUMBER(11) NOT NULL REFERENCES MAGENCY_NEWSPAPER (ID) DEFERRABLE INITIALLY DEFERRED
);

CREATE TABLE MAGENCY_ADVERTISEMENT (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    COMPANY_ID NUMBER(11) NOT NULL REFERENCES AUTH_USER (ID) DEFERRABLE INITIALLY DEFERRED,
    TITLE NVARCHAR2(200),
    VALIDITY DATE NOT NULL,
    MEDIA NVARCHAR2(100)
);

CREATE TABLE MAGENCY_NEWSPAPERAD (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    ADVERTISEMENT_ID NUMBER(11) NOT NULL REFERENCES MAGENCY_ADVERTISEMENT (ID) DEFERRABLE INITIALLY DEFERRED,
    WIDTH DOUBLE PRECISION NOT NULL,
    HEIGHT DOUBLE PRECISION NOT NULL,
    COLOR NUMBER(1) CHECK (COLOR IN (0,1)) NOT NULL
);

ALTER TABLE MAGENCY_NEWSPAPERAD_NEWSPAPERS ADD CONSTRAINT NEWSPAPERAD_ID_REFS_ID_A9F51D0 FOREIGN KEY (NEWSPAPERAD_ID) REFERENCES MAGENCY_NEWSPAPERAD (ID) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE MAGENCY_TELEVISIONAD_PROGRAMS (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    TELEVISIONAD_ID NUMBER(11) NOT NULL,
    PROGRAM_ID NUMBER(11) NOT NULL REFERENCES MAGENCY_PROGRAM (ID) DEFERRABLE INITIALLY DEFERRED,
    UNIQUE (TELEVISIONAD_ID, PROGRAM_ID)
);


CREATE TABLE MAGENCY_TELEVISIONAD (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    ADVERTISEMENT_ID NUMBER(11) NOT NULL REFERENCES MAGENCY_ADVERTISEMENT (ID) DEFERRABLE INITIALLY DEFERRED,
    DURATION NUMBER(11) NOT NULL
);

ALTER TABLE MAGENCY_TELEVISIONAD_PROGRAMS ADD CONSTRAINT TELEVISIONAD_ID_REFS_ID_A10EE2 FOREIGN KEY (TELEVISIONAD_ID) REFERENCES MAGENCY_TELEVISIONAD (ID) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE MAGENCY_BILLBOARDAD_BILLBOARDS (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    BILLBOARDAD_ID NUMBER(11) NOT NULL,
    BILLBOARD_ID NUMBER(11) NOT NULL REFERENCES MAGENCY_BILLBOARD (ID) DEFERRABLE INITIALLY DEFERRED,
    UNIQUE (BILLBOARDAD_ID, BILLBOARD_ID)
);

CREATE TABLE MAGENCY_BILLBOARDAD (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    ADVERTISEMENT_ID NUMBER(11) NOT NULL REFERENCES MAGENCY_ADVERTISEMENT (ID) DEFERRABLE INITIALLY DEFERRED
);


ALTER TABLE MAGENCY_BILLBOARDAD_BILLBOARDS ADD CONSTRAINT BILLBOARDAD_ID_REFS_ID_0FAB013 FOREIGN KEY (BILLBOARDAD_ID) REFERENCES MAGENCY_BILLBOARDAD (ID) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE MAGENCY_WEBSITEAD_WEBSITES (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    WEBSITEAD_ID NUMBER(11) NOT NULL,
    WEBSITE_ID NUMBER(11) NOT NULL REFERENCES MAGENCY_WEBSITE (ID) DEFERRABLE INITIALLY DEFERRED,
    UNIQUE (WEBSITEAD_ID, WEBSITE_ID)
);

ALTER TABLE MAGENCY_WEBSITEAD_WEBSITES ADD CONSTRAINT WEBSITEAD_ID_REFS_ID_8EB71A28 FOREIGN KEY (WEBSITEAD_ID) REFERENCES MAGENCY_WEBSITEAD (ID) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE MAGENCY_BILL (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    ADVERTISEMENT_ID NUMBER(11) NOT NULL REFERENCES MAGENCY_ADVERTISEMENT (ID) DEFERRABLE INITIALLY DEFERRED,
    AMMOUNT DOUBLE PRECISION NOT NULL,
    PAID_BY NVARCHAR2(200),
    TIME TIMESTAMP NOT NULL,
    COMMENT NVARCHAR2(500)
);


CREATE TABLE AUTH_USER (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    PASSWORD NVARCHAR2(128),
    LAST_LOGIN TIMESTAMP NOT NULL,
    USERNAME NVARCHAR2(30),
    NAME NVARCHAR2(200),
    IS_SUPERUSER NUMBER(1) CHECK (IS_SUPERUSER IN (0,1)) NOT NULL,
    EMAIL NVARCHAR2(75) UNIQUE,
    IS_ACTIVE NUMBER(1) CHECK (IS_ACTIVE IN (0,1)) NOT NULL,
    DATE_JOINED TIMESTAMP NOT NULL,
    IS_STAFF NUMBER(1) CHECK (IS_STAFF IN (0,1)) NOT NULL,
    ADDRESS NVARCHAR2(500),
    PHONE NVARCHAR2(500)
);

CREATE TABLE MAGENCY_WEBSITE (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    TITLE NVARCHAR2(200),
    URL NVARCHAR2(255)
);


CREATE TABLE MAGENCY_NEWSPAPERAD_NEWSPAPERS (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    NEWSPAPERAD_ID NUMBER(11) NOT NULL,
    SECTION_ID" NUMBER(11) NOT NULL REFERENCES "MAGENCY_SECTION" ("ID) DEFERRABLE INITIALLY DEFERRED,
    UNIQUE (NEWSPAPERAD_ID", "SECTION_ID)
);

CREATE TABLE MAGENCY_WEBSITEAD (
    ID NUMBER(11) NOT NULL PRIMARY KEY,
    ADVERTISEMENT_ID" NUMBER(11) NOT NULL REFERENCES "MAGENCY_ADVERTISEMENT" ("ID) DEFERRABLE INITIALLY DEFERRED
);